// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
dotenv.config({ path: ".env.local" });
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: [
      process.env["POSTGRES_PRISMA_URL"],
      process.env["NEON_DATABASE_URL"],
      process.env["POSTGRES_URL"],
      process.env["DATABASE_URL"],
    ]
      .map((u) => u?.replace(/\\n/g, "").trim())
      .find((u) => !!u),
  },
});
